const DATA_URL = 'https://raw.githubusercontent.com/dataofjapan/land/master/japan.topojson';
const svg = d3.select('#map');
const compareEqual = d3.select('#compareEqual');
const compareMercator = d3.select('#compareMercator');
const compareWrap = document.querySelector('#compareWrap');
const wrap = document.querySelector('#mapWrap');
const loading = document.querySelector('#loading');
let topology, country, prefectures, prefMesh;
let mode = 'equal';
let centerLon = 150;
let activeRegion = 'all';
let showPref = true, showGrid = true, showLabels = true;
let projection, path, zoom;
let compareZoom;
const g = svg.append('g');
const gridG = g.append('g'), landG = g.append('g'), boundaryG = g.append('g'), labelG = g.append('g'), overlayG = g.append('g');
const regions = {all:null,hokkaido:[139,46,146,41],honshu:[128,42,143,33],shikoku:[132,35,135,32],kyushu:[129,34,132,30],okinawa:[121,31,132,23],north:[140,48,151,42]};
function size(){return [wrap.clientWidth,wrap.clientHeight];}
function targetFeature(){return activeRegion==='all'?country:regionFeature(activeRegion);}
function regionFeature(name){if(!prefectures)return country;const b=regions[name];if(!b)return country;const [minLon,maxLat,maxLon,minLat]=b;const features=prefectures.features.filter(f=>{const [lon,lat]=d3.geoCentroid(f);return lon>=minLon&&lon<=maxLon&&lat>=minLat&&lat<=maxLat;});return features.length?{type:'FeatureCollection',features}:country;}
function buildProjection(type,w,h,target,forcedScale=null){const p=(type==='equal'?d3.geoEqualEarth():d3.geoMercator()).rotate([-centerLon,0,0]);if(forcedScale===null)p.fitExtent([[28,25],[w-28,h-28]],target);else{p.scale(forcedScale);const b=d3.geoPath(p).bounds(target);p.translate([w/2-(b[0][0]+b[1][0])/2,h/2-(b[0][1]+b[1][1])/2]);}return p;}
function drawSingle(){const [w,h]=size();projection=buildProjection(mode==='mercator'?'mercator':'equal',w,h,targetFeature());path=d3.geoPath(projection);[gridG,landG,boundaryG,labelG,overlayG].forEach(x=>x.selectAll('*').remove());if(showGrid){const graticule=d3.geoGraticule().step([10,10]);gridG.append('path').datum(graticule()).attr('class','grid-line').attr('d',path);}landG.append('path').datum(country).attr('class','land').attr('d',path);if(showPref&&prefMesh)boundaryG.append('path').datum(prefMesh).attr('class','pref-boundary').attr('d',path);if(showLabels)drawLabels(labelG,projection);drawScale(overlayG,w,h);setupSingleZoom();svg.call(zoom.transform,d3.zoomIdentity);document.querySelector('#projectionLabel').innerHTML=mode==='equal'?`イコールアース<br><small>Equal Earth / ${centerLon}°E</small>`:`通常の地図<br><small>Mercator / ${centerLon}°E</small>`;document.querySelector('#scaleText').textContent=mode==='equal'?'正積図法：面積を保つ':'比較用：メルカトル図法';}
function drawCompare(){const [fullW,h]=size();const w=Math.max(260,fullW/2);const target=targetFeature();const pe=buildProjection('equal',w,h,target),pm=buildProjection('mercator',w,h,target);const commonScale=Math.min(pe.scale(),pm.scale());drawPane(compareEqual,'equal',w,h,target,commonScale);drawPane(compareMercator,'mercator',w,h,target,commonScale);setupCompareZoom();compareEqual.call(compareZoom.transform,d3.zoomIdentity);document.querySelector('#projectionLabel').innerHTML=`左右比較<br><small>同じ縮尺 / ${centerLon}°E</small>`;document.querySelector('#scaleText').textContent='左右とも同じ縮尺・同じ中央経線';}
function drawPane(sel,type,w,h,target,scale){sel.attr('width',w).attr('height',h);const p=buildProjection(type,w,h,target,scale),pg=d3.geoPath(p),root=sel.selectAll('g').data([0]).join('g');root.selectAll('*').remove();if(showGrid){const gr=d3.geoGraticule().step([10,10]);root.append('path').datum(gr()).attr('class','grid-line').attr('d',pg);}root.append('path').datum(country).attr('class','land').attr('d',pg);if(showPref&&prefMesh)root.append('path').datum(prefMesh).attr('class','pref-boundary').attr('d',pg);if(showLabels)drawLabels(root,p);const title=type==='equal'?'イコールアース':'メルカトル';root.append('text').attr('class','compare-caption').attr('x',16).attr('y',28).text(title);}
function drawLabels(group,p){const labels=[['北海道',142.8,43.5,'region-label'],['本州',138.1,36.4,'region-label'],['四国',133.5,33.7,'region-label'],['九州',130.7,32.2,'region-label'],['沖縄県',127.8,26.3,'region-label'],['日本海',136.2,39.3,'ocean-label'],['太平洋',151,34,'ocean-label'],['東シナ海',124.8,29,'ocean-label'],['オホーツク海',146,48,'ocean-label']];labels.forEach(([text,lon,lat,cls])=>{const q=p([lon,lat]);if(q)group.append('text').attr('class',cls).attr('x',q[0]).attr('y',q[1]).attr('text-anchor','middle').text(text);});[['択捉島',147.1,45],['国後島',145.9,44.1],['色丹島',146.9,43.8],['歯舞群島',146.3,43.5]].forEach(([text,lon,lat])=>{const q=p([lon,lat]);if(q)group.append('text').attr('class','territory-label').attr('x',q[0]+4).attr('y',q[1]).text(text);});const q=p([147,46]);if(q)group.append('text').attr('class','territory-label').attr('x',q[0]+25).attr('y',q[1]+18).text('北方領土');}
function drawScale(group,w,h){const x=30,y=h-30,len=Math.max(90,Math.min(190,w*.18));group.append('line').attr('class','scale-line').attr('x1',x).attr('x2',x+len).attr('y1',y).attr('y2',y);[0,.5,1].forEach(t=>group.append('line').attr('class','scale-line').attr('x1',x+len*t).attr('x2',x+len*t).attr('y1',y-5).attr('y2',y+5));group.append('text').attr('class','scale-label').attr('x',x).attr('y',y-9).text('0');group.append('text').attr('class','scale-label').attr('x',x+len/2).attr('y',y-9).attr('text-anchor','middle').text('500 km');group.append('text').attr('class','scale-label').attr('x',x+len).attr('y',y-9).attr('text-anchor','end').text('1,000 km');}
function setupSingleZoom(){if(!zoom){zoom=d3.zoom().scaleExtent([.65,12]).on('zoom',e=>g.attr('transform',e.transform));svg.call(zoom);}}
function setupCompareZoom(){if(!compareZoom){compareZoom=d3.zoom().scaleExtent([.65,12]).on('zoom',e=>{compareEqual.select('g').attr('transform',e.transform);compareMercator.select('g').attr('transform',e.transform);});compareEqual.call(compareZoom);compareMercator.call(compareZoom);}}
function draw(){if(mode==='compare'){svg.style('display','none');compareWrap.style('display','grid');drawCompare();}else{svg.style('display','block');compareWrap.style('display','none');drawSingle();}}
function updateRegionButtons(){document.querySelectorAll('[data-region]').forEach(b=>b.classList.toggle('active',b.dataset.region===activeRegion));}
async function init(){try{topology=await d3.json(DATA_URL);country=topojson.feature(topology,topology.objects.japan);prefectures=country;prefMesh=topojson.mesh(topology,topology.objects.japan,(a,b)=>a!==b);loading.remove();draw();}catch(err){loading.textContent='地図データの読み込みに失敗しました。通信状態を確認してください。';console.error(err);}}
document.querySelectorAll('input[name="projection"]').forEach(el=>el.addEventListener('change',e=>{mode=e.target.value;draw();}));document.querySelector('#centerLon').addEventListener('input',e=>{centerLon=+e.target.value;draw();});document.querySelector('#prefToggle').addEventListener('change',e=>{showPref=e.target.checked;draw();});document.querySelector('#gridToggle').addEventListener('change',e=>{showGrid=e.target.checked;draw();});document.querySelector('#labelsToggle').addEventListener('change',e=>{showLabels=e.target.checked;draw();});document.querySelectorAll('[data-region]').forEach(b=>b.addEventListener('click',()=>{activeRegion=b.dataset.region;updateRegionButtons();draw();}));document.querySelector('#resetBtn').addEventListener('click',()=>{activeRegion='all';updateRegionButtons();draw();});document.querySelector('#zoomIn').addEventListener('click',()=>{if(mode==='compare')compareEqual.transition().call(compareZoom.scaleBy,1.4);else svg.transition().call(zoom.scaleBy,1.4);});document.querySelector('#zoomOut').addEventListener('click',()=>{if(mode==='compare')compareEqual.transition().call(compareZoom.scaleBy,1/1.4);else svg.transition().call(zoom.scaleBy,1/1.4);});window.addEventListener('resize',()=>draw());init();
